name 'rabbitmqadmin'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Installs the rabbitmqadmin tool.'
long_description 'Installs the rabbitmqadmin tool and provides a set of LWRPs for managing queues and exchanges.'
version '1.1.0'

suggests 'rabbitmq'
suggests 'rabbitmq-cluster'
depends 'poise', '~> 2.0'
depends 'python'
